### ISSUE TITLE
One click option to disable usbcore.autosuspend via kernel arguments

### ISSUE THREAD

**Issue by BaconCatBug** [rpmfusion-infra/fedy#120]
**Is your feature request related to a problem? Please describe.**
Fedora by default has usbcore.autosuspend enabled (value of 2), which causes havoc on Desktop PCs where this really does not need to be a thing. e.g. causing bluetooth game controllers to disconnect after ~120 seconds.

**Describe the solution you'd like**
A one click option to set the `usbcore.autosuspend=-1` kernel argument to all kernels and all future kernels

**Describe alternatives you've considered**
This can be manually done by running the `sudo grubby --args="usbcore.autosuspend=-1" --update-kernel=ALL` command, but this requires the user to know that is the solution and what the problem is. By having a one-click solution, hopefully it can help more people.

**Comment by kwizart** [comment]
Thanks for this request.

To me, in sounds more like a kernel bug. Did anyone tried to contact the fedora kernel team about this kind of issue ?
I tend to think that if a bt game controller is in use, it should prevent suspend from the usb port instead of disable autosuspend for the whole usb sub-system.

Until then would you mind looking to implement a fedy plugin for such purpose ? and submit a PR (I think you got half the job done with the grubby line).


Thanks
